version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      PGUSER: 'otusdbuser'
      USER: 'otusdbuser'
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "otusdbuser"
      POSTGRES_PASSWORD: "otusdb321"
    ports:
      - "5432:5432"
    volumes:
      - //d/Data/data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "vl@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "asdsasdasda"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  habrdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge